# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cea5c02730eededf52374ac7ce46c20e73d4c71d54cb2e9c5eb50514ef7fde8ad514b192dbef395952a94b9f26a2b8510e7ceef7291fbe398937791a349cade

test:
  secret_key_base: 89180cc349b9d11c961c66abfee46748f9a77e7eb14fd90967cce74eed7d239779ab6c84f10d0e097d6323ad613a8bb1b6a2f3e9fbf251a17270f6b6927bbc29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
